### ISSUE TITLE
OPNsense 19.7: "Logging/Targets" broke filterlog RegExes

### ISSUE THREAD

**Issue by Alphakilo** [IRQ10/Graylog-OPNsense_Extractors#1]
Apparently the hostname is prepended to the message:
`gateway filterlog: 23,,,0,pppoe0,match,block,in,4,0x0,,251,20167,0,none,6,tcp,40,000.000.56.252,000.000.137.246,53476,4424,0,S,2051397241,,1024,,`

I've set my Graylog2 instance as target for the filterlog here:
System / Setting / "Logging / targets"

**Edit** GDPR'd the source address

**Comment by IRQ10** [comment]
I will try and take a look, is this a recent change to the message format? What version?

I haven't used Graylog in a little while, as the resources needed for processing became greater over time and simply became too unresponsive and slow to deal with on a resource strapped server.

**Comment by Alphakilo** [comment]
> is this a recent change to the message format? What version?

I think the change were introduced with a new feature in OPNsense 19.7:
MVC: https://github.com/opnsense/core/blob/25df4f28ba11494af5e6a6a8dfe9b8c2454f30ee/src/opnsense/mvc/app/controllers/OPNsense/Syslog/forms/dialogDestination.xml

Service template: https://github.com/opnsense/core/blob/25df4f28ba11494af5e6a6a8dfe9b8c2454f30ee/src/opnsense/service/templates/OPNsense/Syslog/syslog-ng-destinations.conf#L27

The old Syslog remote config is deemed legacy and is planned to be removed in 20.1: https://github.com/opnsense/core/issues/3540

I don't think the Graylog version matters, but I'm using 3.0.2

> Graylog  [...] became too unresponsive and slow to deal with

Oh I feel you. Out of curiosity: What are you currently using?

**Comment by IRQ10** [comment]
Merged your changes into the project, thank you. Depending on what I'm doing I will add or try different tools to complement straight syslog. Graylog is back in my lab now, I will keep an eye on it over the next few days and watch for issues with the updated extractors.
