### ISSUE TITLE
Can't Upload Content Pack

### ISSUE THREAD

**Issue by adamklaff** [IRQ10/Graylog-OPNsense_Extractors#10]
I downloaded all the files from the repo and attempted to upload the JSON file but get the following error:

![image](https://user-images.githubusercontent.com/2294937/133913999-7a4b6411-8195-410b-bda1-b71bb99fbdfb.png)

Should I be importing it differently?

**Comment by IRQ10** [comment]
In Graylog, click dropdown on System/Inputs and select Inputs. Click Manage Extractors on the input you receive OPNsense logs and click "Manage Extractors". Then use the Actions drop down and select Import extractors.

From this screen, you can simply copy and paste the JSON from this project page.
