### ISSUE TITLE
'filterlog' not in message - parsing not applied

### ISSUE THREAD

**Issue by mlazzarotto** [IRQ10/Graylog-OPNsense_Extractors#12]
Hi, I'm running OPNsense 22.1.7 and I'm sending RFC compliant logs to Graylog.  
Problem is, your extractor doesn't work because it looks for _filterlog_ in **message**, while _filterlog_ is in a different field named **application_name**.  
How can I solve it?
![image](https://user-images.githubusercontent.com/8932945/205738644-78c9e7ba-7c73-4880-96cf-aa08e51e77ac.png)

**Comment by subract** [comment]
I've got a PR open that may solve your issue: https://github.com/IRQ10/Graylog-OPNsense_Extractors/pull/11

**Comment by mlazzarotto** [comment]
Your changes are working perfectly, many thanks!
