### ISSUE TITLE
no space between filterlog an [ID] in RFC5424 stream

### ISSUE THREAD

**Issue by aG8uZW4K** [IRQ10/Graylog-OPNsense_Extractors#13]
Hi,
we do not have an space between filterlog an [ID]  in the RFC5424 stream of our OPNSense.
To fit this also the regex_value and condition_value has to be changed from
`^(?i).*\\sfilterlog.+\\[.+\\]\\s(.*)$`
to
`^(?i).*\sfilterlog.*\[.+\]\s(.*)$`

Example:
`<134>Oct 11 22:09:59 DEVICENAME filterlog[69604] 173,,,71e589c53c46eb8f15a57ed5e62e2ea1,IFACE,match,pass,in,4,0x2,0,128,12188,0,DF,6,tcp,52,SRC,DST,58771,8080,0,SEC,1506717858,,8192,,mss;nop;wscale;nop;nop;sackOK`
Versions:
OPNSense: 23.7.5
Graylog: 5.0

best regards

**Comment by IRQ10** [comment]
Updated. If you could please provide the location of the complete OPNsense log reference, or update the one in this project via a pull request that would be most appreciated, thank you. 

Note that Graylog will double escape when exporting, the current version of extractors is tested with OPNsense 23.7.5 and Graylog 5.2.2. The version I post here are built in Graylog and exported after testing to ensure they are parsing properly against the versions I'm running.
