### ISSUE TITLE
Can not import the Content Pack:  wrong json format?

### ISSUE THREAD

**Issue by xabix** [IRQ10/Graylog-OPNsense_Extractors#3]
Hello,

When I import the Content Pack I get this error message:
![image](https://user-images.githubusercontent.com/394407/86462802-86713c00-bd2c-11ea-9acf-49cb3d9a09df.png)

Any idea of the issue?

Thanks
XabiX

OPNsense 20.1.8-amd64
[Graylog-OPNsense_Extractors.txt](https://github.com/IRQ10/Graylog-OPNsense_Extractors/files/4869308/Graylog-OPNsense_Extractors.txt)

**Comment by IRQ10** [comment]
6/27/21 - Updated extractors should address this issue.
