### ISSUE TITLE
Filterlog[xyz]

### ISSUE THREAD

**Issue by skalec** [IRQ10/Graylog-OPNsense_Extractors#4]
I log 3 OPNSense firewalls. One is logs sending like

hostename filterlog: ...

the other twos sending like

hostname filterlog[1234]: ...
or
hostname filterlog[12345]: ...

I have change the REGEX to 

^.*\s?filterlog\[*\d*\]*:\s+(.*)$

The numbers in the square brackets are variable

**Comment by drc-jdunn** [comment]
Here is what I am using with the new version of OPNSense.  Not sure they are 100% correct, but are working for me
OLD
Regular expression: \s?filterlog:\s+(.*)$

OPNsense: IPv4 TCP: ^.*\s?filterlog:\s+.*,(in|out),4,.*,tcp,.*$
OPNsense: IPv4 UDP: ^.*\s?filterlog:\s+.*,(in|out),4,.*,udp,.*$
OPNsense: IPv4 ICMP: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,(?!(request|reply|unreachproto|unreachport|unreach|timexceed|paramprob|redirect|maskreply|needfrag|tstamp|tstampreply)),.*$
OPNsense: IPv4 ICMP Echo Type: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,(request|reply),.*$
OPNsense: IPv4 ICMP Unreachproto: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,unreachproto,.*$
OPNsense: IPv4 ICMP Unreachport: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,unreachport,.*$
OPNsense: IPv4 ICMP Other-Unreachable: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,(unreach|timexceed|paramprob|redirect|maskreply),.*$
OPNsense: IPv4 ICMP Needfrag: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,needfrag,.*$
OPNsense: IPv4 ICMP Tstamp: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,tstamp,.*$
OPNsense: IPv4 ICMP Tstamp-reply: ^.*\s?filterlog:\s+.*,(in|out),4,.*,icmp,.*,tstampreply,.*$
OPNsense: IPv6 TCP: ^.*\s?filterlog:\s+.*,(in|out),6,.*,(?i)(tcp),.*$
OPNsense: IPv6 UDP: ^.*\s?filterlog:\s+.*,(in|out),6,.*,(?i)(udp),.*$
OPNsense: IPv6 ICMP: ^.*\s?filterlog:\s+.*,(in|out),6,.*,ICMPv6,.*$

NEW
Regular expression: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$

OPNsense: IPv4 TCP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,tcp,*$
OPNsense: IPv4 UDP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,udp,*$
OPNsense: IPv4 ICMP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,(?!(request|reply|unreachproto|unreachport|unreach|timexceed|paramprob|redirect|maskreply|needfrag|tstamp|tstampreply)),.*$
OPNsense: IPv4 ICMP Echo Type: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,(request|reply),.*$
OPNsense: IPv4 ICMP Unreachproto: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,unreachproto,.*$
OPNsense: IPv4 ICMP Unreachport: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,unreachport,.*$
OPNsense: IPv4 ICMP Other-Unreachable: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,(unreach|timexceed|paramprob|redirect|maskreply),.*$
OPNsense: IPv4 ICMP Needfrag: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,needfrag,.*$
OPNsense: IPv4 ICMP Tstamp: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,tstamp,.*$
OPNsense: IPv4 ICMP Tstamp-reply: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),4,.*,icmp,.*,tstampreply,.*$
OPNsense: IPv6 TCP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),6,.*,(?i)(tcp),.*$
OPNsense: IPv6 UDP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),6,.*,(?i)(udp),.*$
OPNsense: IPv6 ICMP: ^.*\s?filterlog\[[0-9]+\]:\s+(.*)$+|(in|out),6,.*,ICMPv6,.*$


Hope it helps and other can validate they are correct

**Comment by IRQ10** [comment]
6/27/21 - I believe all the newer versions now use the format "filterlog[NNN]". I am still looking for an update to the OPNsense log format (old one is from Pfsense fork), but believe this issue can be closed with my latest updates.
