### ISSUE TITLE
doesn't work with icmp

### ISSUE THREAD

**Issue by colttt** [IRQ10/Graylog-OPNsense_Extractors#6]
Hello,

it looks like that they change something again. I don't see any ICMP in graylog

from the opnsense it comes the following: 
```
Mar 29 15:13:17 fw-01 filterlog[62408]: 101,,,0,ix0_vlan30,match,block,in,4,0x0,,63,21441,0,DF,1,icmp,84,172.16.100.1,185.220.103.7,datalength=64
```

**Comment by irq10-holding** [comment]
Fixed this in the latest update.

**Comment by IRQ10** [comment]
6/27/21 - Updated extractors should address this issue.
