### ISSUE TITLE
since update, the ICMP/DNS has no csv-converter

### ISSUE THREAD

**Issue by colttt** [IRQ10/Graylog-OPNsense_Extractors#9]
Hi,

did you forget the csv-converter in the `OPNsense Unbound DNS`, `OPNsense: IPv4 ICMP` and `OPNsense: IPv6 ICMP`

**Comment by loren2018tw** [comment]
My OPNsense version is 21.7.1 . I find the csv-converter number of field  is incorrect.

**Comment by IRQ10** [comment]
Update 4.2.2 should correct this, I put the CSV headers back in. Thanks for reporting the issue.

**Comment by IRQ10** [comment]
Note - I have removed the OPNsense Unbound extractor. Lacking a documented format I couldn't get it to work consistently and no longer use it myself to play with finding an extractor that works on all messages.
